### ISSUE TITLE
App for this bundle ID not found

### ISSUE THREAD

**Issue by agnasari** [flexible-agency/react-native-check-version#12]
i got error: {"error": "App for this bundle ID not found."}

when i checked on appstore connect, this apps bundle id is same, why got error not found?

This is bundle id when i console log:
<img width="273" alt="Screen Shot 2021-04-13 at 13 22 18" src="https://user-images.githubusercontent.com/80666249/114505965-595a9e00-9c5b-11eb-9925-457e7fcf9c29.png">

And this is bundle id that i got from apple appstore connect: 
<img width="287" alt="Screen Shot 2021-04-13 at 13 22 24" src="https://user-images.githubusercontent.com/80666249/114506006-68415080-9c5b-11eb-82f0-3eb82c34484a.png">

**Comment by tschoffelen** [comment]
Hi! Is it possible this app is only available in certain countries? In that case, you might need to specify the country parameter (defaults to `us`), to look it up in the right App Store:

```
checkVersion({
   country: 'us'
});
```

**Comment by agnasari** [comment]
Hi, solved!! thank you very much

**Comment by dokselblackbit** [comment]
@tschoffelen  Thx))
