### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by zchwyng** [flexible-agency/react-native-check-version#15]
I'm getting the following error when trying to open version.url with
`Linking.openURL(version.url)`

**Safari cannot open the page because the address is invalid**

My version object looks like this:
`{"bundleId": "com.dahlsjoo.shinner", "country": "us", "lastChecked": "2021-07-16T00:05:22.581Z", "needsUpdate": false, "notes": "Bug fixes", "platform": "ios", "released": "2021-07-01T18:19:45Z", "updateType": null, "url": "https://apps.apple.com/us/app/shinner-skate-spots-videos/id1476836516?uo=4", "version": "1.2.4"}`

**Comment by tschoffelen** [comment]
Hi! I don't think that's directly related to this library, as the payload the library returns seems to contain a valid URL.

Would you be able to share a bit more of your code so that I might be able to give you some pointers?
