### ISSUE TITLE
Error: #<WeakSet> could not be cloned

### ISSUE THREAD

**Issue by studiozocaro** [flexible-agency/react-native-check-version#16]
+ node /Users/flavio/Documents/Lavori/boxshop/boxshopW/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/flavio/Documents/Lavori/boxshop/boxshopW/ios/DerivedData/svogly/Build/Products/Release-iphoneos/main.jsbundle --assets-dest /Users/flavio/Documents/Lavori/boxshop/boxshopW/ios/DerivedData/svogly/Build/Products/Release-iphoneos/Svogly.app
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated

error node_modules/react-native-check-version/index.js: #<WeakSet> could not be cloned.
Error: #<WeakSet> could not be cloned.
    at Object.serialize (v8.js:283:7)
    at _default (/Users/flavio/Documents/Lavori/boxshop/boxshopW/node_modules/@babel/core/lib/transformation/util/clone-deep.js:22:34)
    at normalizeFile (/Users/flavio/Documents/Lavori/boxshop/boxshopW/node_modules/@babel/core/lib/transformation/normalize-file.js:79:36)
    at normalizeFile.next (<anonymous>)
    at run (/Users/flavio/Documents/Lavori/boxshop/boxshopW/node_modules/@babel/core/lib/transformation/index.js:29:50)
    at run.next (<anonymous>)
    at /Users/flavio/Documents/Lavori/boxshop/boxshopW/node_modules/@babel/core/lib/transform-ast.js:26:41
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/flavio/Documents/Lavori/boxshop/boxshopW/node_modules/@babel/core/node_modules/gensync/index.js:251:28)
info Run CLI with --verbose flag for more details.
Command /bin/sh failed with exit code 1

**Comment by tschoffelen** [comment]
Hi, thanks for reporting. I can't reproduce this in a normal RN app.

Would you be able to tell me the following:

* Node version you're using
* Version of React Native you're using
* Any custom metro config you have applied

**Comment by studiozocaro** [comment]
problem with babel after upgrade all package
**I solved  downgrade to 		
"@babel/core": "^7.12.17",
"@babel/runtime": "^7.12.18",**




package.json:
"@babel/core": "^7.12.17",
		"@babel/runtime": "^7.12.18",
		"@react-native-async-storage/async-storage": "^1.15.5",
		"@react-native-community/art": "^1.2.0",
		"@react-native-community/masked-view": "^0.1.11",
		"@react-native-community/toolbar-android": "0.1.0-rc.2",
		"@react-native-firebase/app": "^12.4.0",
		"@react-native-firebase/auth": "^12.4.0",
		"@react-navigation/drawer": "^5.12.5",
		"@react-navigation/native": "^5.9.4",
		"@react-navigation/stack": "^5.14.5",
		"axios": "^0.21.1",
		"babel-plugin-transform-inline-environment-variables": "^0.4.3",
		"core-js": "^3.16.0",
		"detect-libc": "^1.0.3",
		"expo": "^42.0.3",
		"expo-cli": "^4.9.1",
		"firebase": "^8.8.1",
		"lodash": "^4.17.21",
		"moment": "^2.29.1",
		"needle": "^2.8.0",
		"nopt": "^5.0.0",
		"rc": "^1.2.8",
		"react": "17.0.2",
		"react-dom": "^17.0.2",
		"react-native": "0.64.2",
		"react-native-auto-align-scrollview": "^0.1.0",
		"react-native-autoheight-webview": "^1.5.8",
		"react-native-axios": "^0.17.1",
		"react-native-base64": "^0.2.1",
		"react-native-button-component": "^0.2.28",
		"react-native-check-version": "^1.0.9",
		"react-native-clear-cache": "sowlutions/react-native-clear-cache",
		"react-native-device-detection": "^0.2.1",
		"react-native-device-info": "^8.1.5",
		"react-native-drawer": "^2.5.1",
		"react-native-elements": "^3.4.2",
		"react-native-exit-app": "^1.1.0",
		"react-native-fast-image": "^8.3.7",
		"react-native-flip-timer": "0.0.5",
		"react-native-fs": "^2.18.0",
		"react-native-gesture-handler": "^1.10.3",
		"react-native-get-sms-android": "^2.1.0",
		"react-native-hr": "^1.1.4",
		"react-native-image-zoom-viewer": "^3.0.1",
		"react-native-indicators": "^0.17.0",
		"react-native-ionicons": "^4.6.5",
		"react-native-loading-spinner-overlay": "^2.0.0",
		"react-native-material-ui": "^1.30.1",
		"react-native-onesignal": "^4.2.0",
		"react-native-pager-view": "^5.4.0",
		"react-native-paper": "^4.9.2",
		"react-native-reanimated": "^1.13.3",
		"react-native-rename": "^2.9.0",
		"react-native-safe-area-context": "^3.2.0",
		"react-native-screens": "^3.4.0",
		"react-native-scroll-into-view": "^2.0.1",
		"react-native-sms-retriever": "^1.1.1",
		"react-native-spinkit": "^1.5.1",
		"react-native-storage": "^1.0.1",
		"react-native-svg": "^12.1.1",
		"react-native-swipe-gestures": "^1.0.5",
		"react-native-swiper": "^1.6.0",
		"react-native-tiny-toast": "^1.0.7",
		"react-native-vector-icons": "^8.1.0",
		"react-native-web": "^0.17.1",
		"react-native-webview": "^11.6.5",
		"react-redux": "^7.2.4",
		"redux": "^4.1.0",
		"redux-persist": "^6.0.0",
		"redux-thunk": "^2.3.0",
		"rn-swipeable-panel": "^1.2.5",
		"rn-tourguide": "^2.7.1",
		"rn-update-apk": "^5.0.0",
		"smartlook-react-native-wrapper": "^1.2.1",
		"sync-storage": "^0.4.2",
		"url": "^0.11.0",
		"utf8": "^3.0.0"

**Comment by Sikandarkhan** [comment]
> problem with babel after upgrade all package **I solved downgrade to "@babel/core": "^7.12.17", "@babel/runtime": "^7.12.18",**
> 
> package.json: "@babel/core": "^7.12.17", "@babel/runtime": "^7.12.18", "@react-native-async-storage/async-storage": "^1.15.5", "@react-native-community/art": "^1.2.0", "@react-native-community/masked-view": "^0.1.11", "@react-native-community/toolbar-android": "0.1.0-rc.2", "@react-native-firebase/app": "^12.4.0", "@react-native-firebase/auth": "^12.4.0", "@react-navigation/drawer": "^5.12.5", "@react-navigation/native": "^5.9.4", "@react-navigation/stack": "^5.14.5", "axios": "^0.21.1", "babel-plugin-transform-inline-environment-variables": "^0.4.3", "core-js": "^3.16.0", "detect-libc": "^1.0.3", "expo": "^42.0.3", "expo-cli": "^4.9.1", "firebase": "^8.8.1", "lodash": "^4.17.21", "moment": "^2.29.1", "needle": "^2.8.0", "nopt": "^5.0.0", "rc": "^1.2.8", "react": "17.0.2", "react-dom": "^17.0.2", "react-native": "0.64.2", "react-native-auto-align-scrollview": "^0.1.0", "react-native-autoheight-webview": "^1.5.8", "react-native-axios": "^0.17.1", "react-native-base64": "^0.2.1", "react-native-button-component": "^0.2.28", "react-native-check-version": "^1.0.9", "react-native-clear-cache": "sowlutions/react-native-clear-cache", "react-native-device-detection": "^0.2.1", "react-native-device-info": "^8.1.5", "react-native-drawer": "^2.5.1", "react-native-elements": "^3.4.2", "react-native-exit-app": "^1.1.0", "react-native-fast-image": "^8.3.7", "react-native-flip-timer": "0.0.5", "react-native-fs": "^2.18.0", "react-native-gesture-handler": "^1.10.3", "react-native-get-sms-android": "^2.1.0", "react-native-hr": "^1.1.4", "react-native-image-zoom-viewer": "^3.0.1", "react-native-indicators": "^0.17.0", "react-native-ionicons": "^4.6.5", "react-native-loading-spinner-overlay": "^2.0.0", "react-native-material-ui": "^1.30.1", "react-native-onesignal": "^4.2.0", "react-native-pager-view": "^5.4.0", "react-native-paper": "^4.9.2", "react-native-reanimated": "^1.13.3", "react-native-rename": "^2.9.0", "react-native-safe-area-context": "^3.2.0", "react-native-screens": "^3.4.0", "react-native-scroll-into-view": "^2.0.1", "react-native-sms-retriever": "^1.1.1", "react-native-spinkit": "^1.5.1", "react-native-storage": "^1.0.1", "react-native-svg": "^12.1.1", "react-native-swipe-gestures": "^1.0.5", "react-native-swiper": "^1.6.0", "react-native-tiny-toast": "^1.0.7", "react-native-vector-icons": "^8.1.0", "react-native-web": "^0.17.1", "react-native-webview": "^11.6.5", "react-redux": "^7.2.4", "redux": "^4.1.0", "redux-persist": "^6.0.0", "redux-thunk": "^2.3.0", "rn-swipeable-panel": "^1.2.5", "rn-tourguide": "^2.7.1", "rn-update-apk": "^5.0.0", "smartlook-react-native-wrapper": "^1.2.1", "sync-storage": "^0.4.2", "url": "^0.11.0", "utf8": "^3.0.0"

I am still facing this issue. Any suggestions please?
