### ISSUE TITLE
"Not a valid semver version: 2.17" iOS

### ISSUE THREAD

**Issue by faizanbuggy** [flexible-agency/react-native-check-version#17]
I have downloaded the app from the App store with the current version on production (2.3)
But always getting needsUpdate : true
![ss](https://user-images.githubusercontent.com/85244978/134008050-1e515564-7e81-40b8-ac66-3ed69e5d8d1f.png)

What do to here?

**Comment by tschoffelen** [comment]
Hi! Thanks for that, I thought we already dealt with non-semver versions, but apparently not.

I've just pushed a fix for the server component, it might take a few hours due to caching before it will show the expected response.
