### ISSUE TITLE
iOS App version is not latest

### ISSUE THREAD

**Issue by preflower** [flexible-agency/react-native-check-version#23]
My app has been placed in App Store, and `http://itunes.apple.com/lookup?lang=en&bundleId=com.instpower.global&country=us ` is 2.0.0(is latest), but `https://check-version.flexible.agency/ios/com.instpower.global/1.4.3?country=us&cn=1` still return 1.4.3

**Comment by tschoffelen** [comment]
Hi! For me the iTunes lookup endpoint still returns 1.4.3. It might take a bit of time before it propagates everywhere, Apple seems to have some very solid caching in place for that endpoint.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/666220/142824662-3f6192dc-5562-416d-80d8-165e264df977.png">

**Comment by tschoffelen** [comment]
Resolved in #24 by adding cache busting parameter to the iTunes lookup URL.
