### ISSUE TITLE
NeedsUpdate showing wrong result

### ISSUE THREAD

**Issue by jiteshs7** [flexible-agency/react-native-check-version#26]
const version = await checkVersion({
      bundleId:'africa.xxx.xx',
      currentVersion:'1.0',
    });
    // currentVersion 1.0.2 , picking correctly from play Store
console.log(version.needsUpdate) // false

**Comment by tschoffelen** [comment]
Hi! `needsUpdate` uses the `semver` library to compare version numbers, so it only works correctly for valid semantic version numbers (`x.x.x`). `1.0.2` is a valid semver, but `1.0` is not, so I can imagine it struggles to do the comparison correctly.

**Comment by jiteshs7** [comment]
hi, thanks for quick reply I'll fix it to make it comparable
