### ISSUE TITLE
help IOS version check

### ISSUE THREAD

**Issue by maoryadin** [flexible-agency/react-native-check-version#27]
Currently how can i check my current app version? when i am trying through DeviceInfo.getVersion() its retrieve the build version.

**Comment by tschoffelen** [comment]
DeviceInfo is a separate package. Please see the README on how to use this package.

**Comment by maoryadin** [comment]
Well based on the readme:

string currentVersion: version to check against, defaults to the currently installed version


Where can i find more info regarding the "currently installed version"? Ios have internal build version, and appStore version, the library check the device version (based build version i guess..) against the appStore version, and it can cause mismatch
