### ISSUE TITLE
[Question] Have you changed anything in the backend after Google Play Store UI update?

### ISSUE THREAD

**Issue by M4Tdev** [flexible-agency/react-native-check-version#30]
Hi, a couple of days ago Google introduced a new design to their Google Play Store, and it broke another similar package that allows getting the currently available version from the store. Did you do any changes to the match of the "Current Version" to adjust for the design changes? If so, could you provide does changes or the whole code to get the store version? Because I would prefer to implement it on the mobile side instead of reaching to a separate backend.

**Comment by M4Tdev** [comment]
Thanks for the fast reply! Yeah, they have made it harder for us, that is basically why I reach out I thought maybe you have found a way to scrape it 😅.

I'm going to try and find some solution for this and if I find one I will let you know and create PR for sure!

**Comment by ramirezjag00** [comment]
for experimentation purposes, as an alternative to google play store redesign, I tried getting the version in an app's page with `apkcombo.com` and it works

**Comment by tschoffelen** [comment]
That was super helpful @ramirezjag00!

I've just pushed a new version of the package that uses this website for Android version checking, as a quick fix until we find a better way to query Google Play directly.

@M4Tdev the master branch of the package now does no longer rely on a custom backend.

**Comment by AlixH** [comment]
> That was super helpful @ramirezjag00!
> 
> I've just pushed a new version of the package that uses this website for Android version checking, as a quick fix until we find a better way to query Google Play directly.
> 
> @M4Tdev the master branch of the package now does no longer rely on a custom backend.

@tschoffelen , are you able to explain why it is working again on iOS (and did not before your backend update) if only Google Play Store changed their API ?

**Comment by tschoffelen** [comment]
I think my backend service might have been overwhelmed with the number of failing Android version checks. We have a couple of million requests per day at the moment.

Yet another reason to update to 1.0.14, which is now fully self-contained, without any reliance on my servers.

**Comment by niyasc** [comment]
How reliable is apkcombo.com? I'm getting network error with the latest updated.
`{"message":"Network Error","name":"AxiosError","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"FormData":null},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36"},"method":"get","url":"https://apkcombo.com/x/....../"},"code":"ERR_NETWORK","status":null}`

Also, the page shows secure connection failed on browser.

**Comment by tschoffelen** [comment]
Turns out not super reliable, that's why I replaced it yesterday by a method to query Google Play directly again (in v1.0.14).

**Comment by M4Tdev** [comment]
Yeah, the solution with apkcombo.com is not good, on Friday I was having problems that apkcombo.com did not have the latest app version, my latest version is 1.29.9 but it was giving me something like 1.9.1.

**Comment by tschoffelen** [comment]
Yes, the latest version of this library now directly scrapes Google Play.

Changelog: https://github.com/flexible-agency/react-native-check-version#changelog
