### ISSUE TITLE
The check version method issue

### ISSUE THREAD

**Issue by Boukadida-Firas** [flexible-agency/react-native-check-version#32]
this.appVersion = await checkVersion(); 
The app crashes when I called this method, I think it is due to your updates 3 hours ago.

**Comment by Boukadida-Firas** [comment]
Yes i hope the issue will be fixed as soon as possible

**Comment by BrunoNepre** [comment]
I'm going to disable my applications, I can't trust

**Comment by tschoffelen** [comment]
Hi both. Google Play has updated their page layouts, which means our custom back-end can't read the latest version anymore.

Instead, we've updated the library to now do this check in-app. Updating the library should resolve this issue. Please see #30.

**Comment by BrunoNepre** [comment]
Looks like Google fixed it, it is working now ! @tschoffelen

**Comment by tschoffelen** [comment]
I've patched our custom back-end to return a successful response for now for Android users, to prevent crashes for developers who are using this library without catching errors returned. It will always return `false` however for `needsUpdate`.

Please update to a new version of the library as soon as possible to restore actual functionality.

**Comment by Boukadida-Firas** [comment]
Thanks a lot
