### ISSUE TITLE
problem severity 1

### ISSUE THREAD

**Issue by BrunoNepre** [flexible-agency/react-native-check-version#33]
Updated this.appVersion = await checkVersion(); fail.

Something was used in this method that stopped a super critical application.

The app is crashing

Help me

**Comment by AlixH** [comment]
Critical as well

**Comment by BrunoNepre** [comment]
@tschoffelen can you help us?

**Comment by AlixH** [comment]
@BrunoNepre have you tried upgrading to the latest version ?

**Comment by BrunoNepre** [comment]
Can you tell me what was changed? I can't access previous tags. I have a critical application stopped and Apple may take up to 48 hours to update the version. my users will be all this time with the app crashed, complicated

**Comment by AlixH** [comment]
Looks like Google fixed it, it is working now !

**Comment by ClaudeROSSI** [comment]
right ... it is working again

**Comment by BrunoNepre** [comment]
I tested it here and it worked. Thanks.

**Comment by tschoffelen** [comment]
Cross-posting from #32:

> I've patched our custom back-end to return a successful response for now for Android users, to prevent crashes for developers who are using this library without catching errors returned. It will always return `false` however for `needsUpdate`.
> 
> Please update to a new version of the library as soon as possible to restore actual functionality.

**Comment by AlixH** [comment]
> Cross-posting from #32:
> 
> > I've patched our custom back-end to return a successful response for now for Android users, to prevent crashes for developers who are using this library without catching errors returned. It will always return `false` however for `needsUpdate`.
> > Please update to a new version of the library as soon as possible to restore actual functionality.

It also seems to be fixed for iOS ?
