### ISSUE TITLE
Publish 1.0.14 tag to npm

### ISSUE THREAD

**Issue by cheunjm** [flexible-agency/react-native-check-version#34]
Thanks for a great library.

Can you publish 1.0.14 tag to npm? It seems like the latest tag published is 1.0.12:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/2954778/170916465-ee2f31fa-21a5-465e-8770-4d6cecf14dc2.png">
<img width="604" alt="image" src="https://user-images.githubusercontent.com/2954778/170916524-cc46b178-4737-43d7-9a01-dae8dff6d7f7.png">

Thanks a lot.

**Comment by tschoffelen** [comment]
Apologies! Now published as `react-native-check-version@1.0.14`
