### ISSUE TITLE
 Does not return IOS information

### ISSUE THREAD

**Issue by junioroga** [flexible-agency/react-native-check-version#9]
Every application I try to search for returns saying "App for this bundle ID not found.".
Am I doing something wrong?
![Captura de Tela 2021-01-31 às 13 08 21](https://user-images.githubusercontent.com/7414393/106390229-2330b080-63c6-11eb-8a5f-5df13be0d728.png)
![Captura de Tela 2021-01-31 às 13 11 32](https://user-images.githubusercontent.com/7414393/106390235-2c218200-63c6-11eb-89b0-c77519e9340e.png)

**Comment by tschoffelen** [comment]
Hi @junioroga!

Just checked a few apps, and it does seem to be working for me:
https://check-version.flexible.agency/ios/nl.hoyapp.mobile/1.0.0

A few things I can think of:

1. Is the app public in the App Store yet?
2. Is the app limited to specific countries perhaps?
3. Is the bundle ID on iOS the same as Android? It doesn't necessarily need to be.

**Comment by junioroga** [comment]
Wow, I need to apologize lol, really, the ios bundle is different.
That's the problem. The application works just fine.
I have just one more question, in a high volume of access, does the query api have a limit on requests?

**Comment by tschoffelen** [comment]
No worries!

There is a limit, but it's IP-based and you won't be able hit it with any normal usage, as there is a CDN that sits on top of the API and caches the requests, so that most calls actually don't hit the origin server.

As we use AWS CloudFront and Lambda for the setup, it scales to near-infinity :)

We have a few apps using this API with 1M+ downloads, so it's proven to be pretty stable.

**Comment by amm297** [comment]
Hi @tschoffelen 

There is any update in this? my android app works fine but for the iOs one i'm getting the error

**Comment by tschoffelen** [comment]
This turned out to not be a problem with our service, but with the bundle ID used. Are you sure you're using the correct bundle ID and the app is publicly available?

**Comment by hoangthuan197** [comment]
Hi @tschoffelen 
I tested with my bundle id apps ( old or just release some days ) but some of them got this errors 
And Android always works fine !

**Comment by tschoffelen** [comment]
Check to see if you need to specify a `country` parameter to the library. By default the library will check the US App Store, so if your app is not available in the US, you won't be able to get version information back.
